USE assignment5;

SHOW tables;

DELIMITER $$
CREATE TRIGGER tasks_bef_ins BEFORE INSERT
ON tasks
FOR EACH ROW
BEGIN
    SET NEW.firstname = TRIM(NEW.FIRSTNAME);
    SET NEW.LASTNAME = TRIM(NEW.LASTNAME);
    SET NEW.JOBID = UPPER(NEW.JOBID);
END ; $$
DELIMITER ;
