DELIMITER $$
CREATE TRIGGER OlaUber BEFORE UPDATE
ON task3
FOR EACH ROW
BEGIN
    SET NEW.TOTAL = NEW.SUB1 + NEW.SUB2 + NEW.SUB3 + NEW.SUB4 + NEW.SUB5;
    SET NEW.PER_MARKS = NEW.TOTAL/5;
    IF NEW.PER_MARKS >=90 THEN
        SET NEW.GRADE = 'EXCELLENT';
    ELSEIF NEW.PER_MARKS>=75 AND NEW.PER_MARKS<90 THEN
        SET NEW.GRADE = 'VERY GOOD';
    ELSEIF NEW.PER_MARKS>=60 AND NEW.PER_MARKS<75 THEN
        SET NEW.GRADE = 'GOOD';
    ELSEIF NEW.PER_MARKS>=40 AND NEW.PER_MARKS<60 THEN
        SET NEW.GRADE = 'AVERAGE';
    ELSE SET NEW.GRADE = 'NOT PROMOTED';
    END IF;
END; $$
DELIMITER ;
